---

- name: config
  vars:
    run_wsl: |
      ansible-playbook \
        --ask-become-pass \
        --inventory $PWD/ansible \
        $PWD/../../../linux/redhat-config/nfs-server/install-kernel/ansible-playbook.config.yml
  hosts: nfs-server
  become: true
  tasks:

    - name: install the nfs package
      ansible.builtin.yum:
        name: 
          - nfs-utils
          - nfs4-acl-tools
        state: present
      register: package_result
      until: "package_result is not failed"
      retries: 3
      delay: 5
