version: '3.3'

networks:
  external_net-influxdb:
    external: true

configs:
  stack_cfg-influxdb.conf:
    file: ./config/influxdb.conf

volumes:
  stack_vol-influxdb:

services:
  influxdb:
    image: influxdb:1.8
    env_file: external_env-influxdb.env
    configs:
      - source: stack_cfg-influxdb.conf
        target: /etc/influxdb/influxdb.conf
    volumes:
      - stack_vol-influxdb:/var/lib/influxdb
    ports:
      - target: 8086
        published: 8086
        protocol: tcp
        mode: host
      # - 2003:2003
      # - 25826:25826
      # - 4242:4242
      # - 8088:8088
      # - 8089:8089
    networks:
      - external_net-influxdb
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.influxdb-node == true
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 120s
