---

- name: run
  vars:
    run_wsl: |
      ansible-playbook \
        --ask-become-pass \
        --inventory $PWD/ansible \
        $PWD/../../../linux/any-job/shutdown/ansible-playbook.run.yml
  hosts: linux
  become: yes
  tasks: 
  
    - name: shutdown the server
      ansible.builtin.shell: "shutdown now"
      become: yes
      async: 1
      poll: 0
