---

- name: config
  vars:
    run_wsl: |
      ansible-playbook \
        --ask-become-pass \
        --inventory $PWD/ansible \
        $PWD/../../../linux/redhat-config/docker/install-ce/ansible-playbook.config.yml
  hosts: docker
  become: true
  tasks: 

    - name: set docker_distribution
      ansible.builtin.set_fact:
        docker_distribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"

    - name: add docker GPG rpm key
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/{{ docker_distribution }}/gpg"
        state: present

    - name: add docker yum repository
      ansible.builtin.yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/{{ docker_distribution }}/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/{{ docker_distribution }}/gpg"

    - name: update yum and install docker-ce
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: true
      register: yum_result
      until: "yum_result is not failed"
      retries: 3
      delay: 5

    - name: start Docker
      ansible.builtin.service:
        name: "docker"
        enabled: true
        state: started
