---

- name: config
  vars:
    run_wsl: |
      ansible-playbook \
        --ask-become-pass \
        --inventory $PWD/ansible \
        $PWD/../../../linux/any-config/apt/sources/ansible-playbook.config.yml
  hosts: linux
  become: true
  tasks: 
  
    - name: wrong packager
      when: 
        - apt.sources.check | default(true) | bool
        - ansible_pkg_mgr != 'apt'
      ansible.builtin.fail:
        msg: just for apt packager not '{{ ansible_pkg_mgr }}'
  
    - name: sed replace apt sources
      loop: "{{ apt.sources.sed | default([]) | list }}"
      vars:
        _expression: "{{ item.expression | default(None) }}"
        _file: "{{ item.file | default(None) }}"
      when: 
        - _expression != None
        - _file != None
      ansible.builtin.shell: "sudo sed \
        -e '{{ _expression }}' \
        -i.bak \
        {{ _file }}"

    - name: lineinfile replace apt sources
      loop: "{{ apt.sources.lineinfile | default([]) | list }}"
      vars:
        _default: 
          backup: true
        _lineinfile: "{{ item | combine(_default, recursive=True) }}"
      ansible.builtin.lineinfile: "{{ _lineinfile }}"

    - name: copy replace apt sources
      loop: "{{ apt.sources.cp | default([]) | list }}"
      vars:
        _default: 
          backup: true
        _copy: "{{ item | combine(_default, recursive=True) }}"
      ansible.builtin.copy: "{{ _copy }}"

    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes