---

- name: deploy
  vars:
    run_wsl: |
      ansible-playbook \
        --inventory $PWD/ansible \
        $PWD/../../../docker/stack-replication-master-slave/tonimoreno-influxdb-srelay/ansible-playbook.deploy.yml
  hosts: docker-manager[0]
  tasks: 

    - name: set ws_dir
      include_tasks: "{{ playbook_dir }}/../../../.seed/ansible-tasks/ws-dir.set.yml"
      vars: 
        dir: "{{ playbook_dir }}/../../../"

    - name: set dir_name
      include_tasks: "{{ ws_dir }}/.seed/ansible-tasks/dir-name.set.yml"

    - name: copy dir_path
      include_tasks: "{{ ws_dir }}/.seed/ansible-tasks/dir-path.copy.yml"

    - name: overwrite dir_copy
      loop: "{{ influxdb.dir_copy }}"
      when: item.src is defined
      ansible.builtin.copy: "{{ item }}"

    - name: add swarm label
      include_tasks: "{{ ws_dir }}/.seed/ansible-tasks/docker-label.add.yml"
      vars:
        labels: "{{ influxdb.lab }}"

    - name: add external_net
      include_tasks: "{{ ws_dir }}/.seed/ansible-tasks/docker-networks.add.yml"
      vars:
        networks: "{{ influxdb.net }}"

    - name: build env_file
      include_tasks: "{{ ws_dir }}/.seed/ansible-tasks/docker-envs.create.yml"
      vars:
        envs: 
          - dest: "{{ dir_path }}/external_env-master.env"
            data: "{{ influxdb.env.master }}"
          - dest: "{{ dir_path }}/external_env-slave.env"
            data: "{{ influxdb.env.slave }}"
          - dest: "{{ dir_path }}/external_env-srelay.env"
            data: "{{ influxdb.env.srelay }}"
          - dest: "{{ dir_path }}/external_env-syncflux.env"
            data: "{{ influxdb.env.syncflux }}"

    - name: add stack service
      include_tasks: "{{ ws_dir }}/.seed/ansible-tasks/docker-compose.add.yml"
      vars:
        compose:
          type: stack
          name: "{{ dir_name[0] }}"
          path: "{{ dir_path }}"
          files: 
            - "docker-compose-swarm.yml"
