---

- name: deploy
  vars:
    run_wsl: |
      ansible-playbook \
        --inventory $PWD/ansible \
        $PWD/../../../docker/stack-replication-master-slave/tonimoreno-influxdb-srelay/ansible-playbook.deploy.yml
  hosts: docker-manager[0]
  tasks: 

    - name: set ws
      include_tasks: "{{ playbook_dir }}/../../../.seed/ansible-tasks/ws.set.yml"

    - name: set dir
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/dir.set.yml"

    - name: copy dir
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/dir.copy.yml"
      vars:
        copys: "{{ influxdb.dir_copy }}"

    - name: add swarm label
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-label.add.yml"
      vars:
        labels: "{{ influxdb.lab }}"

    - name: add external_net
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-networks.add.yml"
      vars:
        networks: "{{ influxdb.net }}"

    - name: build env_file
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-envs.create.yml"
      vars:
        envs: 
          - dest: "{{ dir.remote }}/external_env-master.env"
            data: "{{ influxdb.env.master }}"
          - dest: "{{ dir.remote }}/external_env-slave.env"
            data: "{{ influxdb.env.slave }}"
          - dest: "{{ dir.remote }}/external_env-srelay.env"
            data: "{{ influxdb.env.srelay }}"
          - dest: "{{ dir.remote }}/external_env-syncflux.env"
            data: "{{ influxdb.env.syncflux }}"

    - name: add stack service
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-compose.add.yml"
      vars:
        compose:
          type: stack
          name: "{{ dir.names[0] }}"
          path: "{{ dir.remote }}"
          files: 
            - "docker-compose-swarm.yml"
