version: '3.3'

networks:
  external_net-influxdb:
    external: true

configs:
  stack_cfg-influxdb.conf:
    file: ./config/influxdb.conf
  stack_cfg-syncflux.toml:
    file: ./config/syncflux.toml
  stack_cfg-influxdb-srelay.conf:
    file: ./config/influxdb-srelay.conf
    
volumes:
  stack_vol-influxdb:
  stack_vol-syncflux-log:
  # stack_vol-syncflux-conf:

services:
  master:
    image: influxdb:1.8
    env_file: external_env-master.env
    configs:
      - source: stack_cfg-influxdb.conf
        target: /etc/influxdb/influxdb.conf
    volumes:
      - stack_vol-influxdb:/var/lib/influxdb
    ports:
      - target: 8086
        published: 8086
        protocol: tcp
        mode: host
      # - 2003:2003
      # - 25826:25826
      # - 4242:4242
      # - 8088:8088
      # - 8089:8089
    networks:
      - external_net-influxdb
    healthcheck:
      test: ["curl", "-f", "http://localhost:8086/ping"]
      interval: 1m
      timeout: 10s
      retries: 5
      # HEALTHCHECK --interval=5s --retries=24 --timeout=1s CMD curl -sI 127.0.0.1:8086/ping | grep -q "204 No Content"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.influxdb-node == master
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 120s
      endpoint_mode: dnsrr 

  slave:
    image: influxdb:1.8
    env_file: external_env-slave.env
    configs:
      - source: stack_cfg-influxdb.conf
        target: /etc/influxdb/influxdb.conf
    volumes:
      - stack_vol-influxdb:/var/lib/influxdb
    ports:
      - target: 8086
        published: 8086
        protocol: tcp
        mode: host
      # - 2003:2003
      # - 25826:25826
      # - 4242:4242
      # - 8088:8088
      # - 8089:8089
    networks:
      - external_net-influxdb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.influxdb-node == slave
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 120s
      endpoint_mode: dnsrr 
        
  srelay:
    image: tonimoreno/influxdb-srelay:0.6.1
    env_file: external_env-srelay.env
    configs:
      - source: stack_cfg-influxdb-srelay.conf
        target: /etc/influxdb-srelay/influxdb-srelay.conf
    ports:
      - target: 8086
        published: 8086
        protocol: tcp
        mode: host
    networks:
      external_net-influxdb:
        aliases:
          - influxdb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.influxdb-srelay == true
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 120s
        
  syncflux:
    image: tonimoreno/syncflux:v0.7.0
    env_file: external_env-syncflux.env
    configs:
      - source: stack_cfg-syncflux.toml
        target: /opt/syncflux/conf/syncflux.toml
    volumes:
      - stack_vol-syncflux-log:/opt/syncflux/log
      # - stack_vol-syncflux-conf:/opt/syncflux/conf
    ports:
      - target: 4090
        published: 54090
        protocol: tcp
        mode: ingress
    networks:
      - external_net-influxdb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.labels.influxdb-syncflux == true
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 120s
