---

- name: config
  vars:
    run_wsl: |
      ansible-playbook \
        --ask-become-pass \
        --inventory $PWD/ansible \
        $PWD/../../../linux/redhat-config/firewalld/trusted-interface/ansible-playbook.config.yml
  hosts: linux
  become: true
  tasks:

    # bug maybe
    # - name: change interface to trusted zone
    #   loop: "{{ firewalld.trusted_interface }}"
    #   ansible.posix.firewalld:
    #     zone: trusted
    #     interface: "{{ item }}"
    #     permanent: yes
    #     state: enabled

    - name: change interface to trusted zone
      loop: "{{ firewalld.public_service }}"
      shell: "firewall-cmd --permanent --zone=trusted --change-interface={{ item }}" 

    - name: reload firewall
      shell: "firewall-cmd --reload"  
