---

- name: deploy
  vars:
    run_wsl: |
      ansible-playbook \
        --ask-become-pass \
        --inventory $PWD/ansible \
        $PWD/../../../docker/stack-standalone-failover/grafana-grafana-ui/ansible-playbook.deploy.yml
  hosts: "{{ 'nfs-client:&docker-grafana-node' if (groups['docker-grafana-node'] is defined) else 'nfs-client' }}"
  tasks:

    - name: set ws
      include_tasks:
        file: "{{ playbook_dir }}/../../../.seed/ansible-tasks/ws.set.yml"
        # https://github.com/ansible/ansible/issues/72099
        apply:
          run_once: true

    - name: set dir
      include_tasks:
        file: "{{ ws.local }}/.seed/ansible-tasks/dir.set.yml"
        apply:
          run_once: true

    - name: wait nfs mount
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/nfs-mount.wait.yml"
      vars:
        _default:
          - name: on_manager
            point: "/grafana-lib"
            mount: "/mnt/nfs/grafana-lib"
            option: "vers=4,loud,rw,sync"
            unmount: true
            retry: 5
          - name: on_manager
            point: "/grafana-dashboards"
            mount: "/mnt/nfs/grafana-dashboards"
            option: "vers=4,loud,rw,sync"
            unmount: true
            retry: 5
        wait_nfs: "{{ grafana.nfs_wait | default(_default) }}"


- name: deploy
  hosts: "{{ 'docker:&docker-grafana-node' if (groups['docker-grafana-node'] is defined) else 'docker' }}"
  tasks:

    - name: set ws
      when: ws is undefined
      include_tasks:
        file: "{{ playbook_dir }}/../../../.seed/ansible-tasks/ws.set.yml"
        # https://github.com/ansible/ansible/issues/72099
        apply:
          run_once: true

    - name: set dir
      when: dir is undefined
      include_tasks:
        file: "{{ ws.local }}/.seed/ansible-tasks/dir.set.yml"
        apply:
          run_once: true

    - name: copy dir
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/dir.copy.yml"
      vars:
        copys: "{{ grafana.dir_copy | default([],true) }}"

    - name: add external_vol
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-volumes.add.yml"
      vars:
        volumes: "{{ grafana.vol | default([],true) }}"

    - name: add external_net
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-networks.add.yml"
      vars:
        networks: "{{ grafana.net | default([],true) }}"


- name: deploy
  hosts: docker-manager
  run_once: true
  tasks:

    - name: set ws
      when: ws is undefined
      include_tasks: "{{ playbook_dir }}/../../../.seed/ansible-tasks/ws.set.yml"

    - name: set dir
      when: dir is undefined
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/dir.set.yml"

    - name: copy dir
      when: not (dir.synchronized | default(false) | bool)
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/dir.copy.yml"
      vars:
        copys: "{{ grafana.dir_copy | default([],true) }}"

    - name: add swarm label
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-label.add.yml"
      vars:
        labels: "{{ grafana.lab | default([],true) }}"

    # - name: add swarm secret
    #   include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-secrets.add.yml"
    #   vars:
    #     secrets: "{{ grafana.sec | default([],true) }}"

    # - name: add swarm config
    #   include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-configs.add.yml"
    #   vars:
    #     configs: "{{ grafana.cfg | default([],true) }}"

    - name: build env_file
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-envs.create.yml"
      vars:
        envs:
          - dest: "{{ dir.remote }}/external_env-grafana.env"
            data: "{{ grafana.env | default([],true) }}"

    - name: add stack service
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-compose.add.yml"
      vars:
        compose:
          type: stack
          name: "{{ dir.names[0] }}"
          path: "{{ dir.remote }}"
          files:
            - "docker-compose-swarm.yml"
