---

- name: config
  vars:
    run_wsl: |
      ansible-playbook \
        --ask-become-pass \
        --inventory $PWD/ansible \
        $PWD/../../../linux/any-config/pip/sources/ansible-playbook.config.yml
  hosts: linux
  become: true
  tasks: 

    - name: install python3-pip
      become: true
      ansible.builtin.package:
        name: python3-pip
        state: present
      register: package_result
      until: "package_result is not failed"
      retries: 3
      delay: 5

    - name: update pip use mirror
      when: 
        - pip.mirror is defined
      ansible.builtin.shell: "python3 -m pip install -i {{ pip.mirror }} --upgrade pip"
      register: pip_result
      until: "pip_result is not failed"
      retries: 3
      delay: 5
  
    - name: set pip sources mirror
      when: 
        - pip.mirror is defined
      ansible.builtin.shell: "pip3 config set global.index-url {{ pip.mirror }}"
