---

- name: deploy
  vars:
    run_wsl: |
      ansible-playbook \
        --ask-become-pass \
        --inventory $PWD/ansible \
        $PWD/../../../docker/stack-standalone/grafana-grafana-ui/ansible-playbook.deploy.yml
  hosts: docker-manager[0]
  tasks:

    - name: set ws
      include_tasks: "{{ playbook_dir }}/../../../.seed/ansible-tasks/ws.set.yml"

    - name: set dir
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/dir.set.yml"

    - name: copy dir
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/dir.copy.yml"
      vars:
        copys: "{{ grafana.dir_copy }}"

    - name: add swarm label
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-label.add.yml"
      vars:
        labels: "{{ grafana.lab }}"

    - name: add external_net
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-networks.add.yml"
      vars:
        networks: "{{ grafana.net }}"
  
    # TODO add exports

    - name: wait nfs mount
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/nfs-mount.wait.yml"
      vars:
        _default:
          on_manager:
            point: "/grafana-dashboards"
            mount: "/mnt/nfs/grafana-dashboards"
            option: "vers=4,loud,rw,sync"
            unmount: true
            retry: 5
        wait_nfs: "{{ grafana.dashboards.nfs_wait | default(_default) }}"

    - name: build env_file
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-envs.create.yml"
      vars:
        envs: 
          - dest: "{{ dir.remote }}/external_env-grafana.env"
            data: "{{ grafana.env }}"

    - name: add stack service
      include_tasks: "{{ ws.local }}/.seed/ansible-tasks/docker-compose.add.yml"
      vars:
        compose:
          type: stack
          name: "{{ dir.names[0] }}"
          path: "{{ dir.remote }}"
          # files: 
          #   - "docker-compose-swarm.yml"
          template: 
            name: "docker-compose-swarm"
            opt:
              src: "{{ dir.local }}/docker-compose-swarm.yml.j2"
              dest: "{{ dir.remote }}/docker-compose-swarm.yml"
            vars:
              NFS_ADDR: "{{ grafana.bind_addr }}"
